export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PAGE_LIMIT: "SET_PAGE_LIMIT",
  RECEIVE_ARTWORK_PAGE: "RECEIVE_ARTWORK_PAGE",
  SEARCH_ARTWORK: "SEARCH_ARTWORK",
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_DETAILS: "FETCH_DETAILS",
  SET_REMOVE_TOGGLE: "SET_REMOVE_TOGGLE",
  SET_PRODUCT_FAVOURITES: "SET_PRODUCT_FAVOURITES",
};
